---
title: "Task 15"
author: "Gideon Miles"
date: "`r format(Sys.time(), '%B %d, %Y')`"
output:
  html_document:  
    keep_md: true
    toc: true
    toc_float: true
    code_folding: hide
    fig_height: 6
    fig_width: 12
    fig_align: 'center'
---

```{r, echo=FALSE}
knitr::opts_chunk$set(echo = TRUE, message = FALSE, warning = FALSE)
```

```{r load_libraries, include=FALSE}
# Use this R-Chunk to load all your libraries!
#install.packages("tidyverse") # run this line once in console to get package
library(tidyverse)

```

```{r load_data}
# Use this R-Chunk to import all your datasets!

Waitlist<-read_csv("https://byuistats.github.io/M335/data/waitlist_DP_108.csv")

library(lubridate)

waitlist2<-Waitlist %>% 
  rename(
    semester_term_code=`Semester Term Code`,
    person_id=`person ID`,
    course_sec=`Course Sec`,
    registration_date=`Registration Date`,
    waitlist_reason=`Waitlist Reason`
  ) %>% 
mutate(date=mdy_hm(registration_date))

sec18<-waitlist2 %>% filter(course_sec=="FDMAT108-18")


registered_from_waitlist<- function(transaction_data) {
   ##instead of sec18 put transaction data.
  
  
}




dat1<-sec18 %>% arrange(person_id, desc(date), desc(Status)) %>% View()
 distinct(person_id, .keep_all = TRUE) %>% 
 summarise(registered= sum(Status=="Registered"),
 reg_from_wl=sum(waitlist_reason=="Waitlist Registered", na.rm=TRUE))
 
 dat1$req_from_w1/dat1$registered
 
 
 
 registered_from_waitlist(transaction_data = )
 
 
 
 
 wlist<-sec15 %>% 
   filter(Status=="Wait List") %>% 
   distinct(person_id) %>% 

   
 
   
 
 reg_from_wl wlist %>% nrow()
 
```

## Background

_Place Task Background Here_

## Data Wrangling

```{r tidy_data}
# Use this R-Chunk to clean & wrangle your data!

```

## Data Visualization

```{r plot_data}
# Use this R-Chunk to plot & visualize your data!

```

## Conclusions
