---
title: "CASE STUDY TITLE"
author: "YOUR NAME"
date: "`r format(Sys.time(), '%B %d, %Y')`"
output:
  html_document:  
    keep_md: true
    toc: true
    toc_float: true
    code_folding: hide
    fig_height: 6
    fig_width: 12
    fig_align: 'center'
---

```{r, echo=FALSE}
knitr::opts_chunk$set(echo = TRUE, message = FALSE, warning = FALSE)
```

```{r load_libraries, include=FALSE}
# Use this R-Chunk to load all your libraries!
#install.packages("tidyverse") # run this line once in console to get package
library(tidyverse)
library(ourworldindata)

```

```{r load_data}
# Use this R-Chunk to import all your datasets!
c1<-child_mortality

 

  c2<-c1 %>% na.omit()
   
c2<-c2 %>% group_by(year,continent) %>% mutate(continentaverage=mean(deaths_per_woman))


   ggplot(c1, aes(x=year, y=(deaths_per_woman), color = continent)) +
 geom_point()+
  ylab("Mortality Rates")+
  ggtitle("Mortality Rate by Continent")+     geom_smooth(color="black", se=F)+
     facet_grid(~continent)





  
## Idea Geom point faceted by continet 
  
  
```

## Background

_Place Task Background Here_

## Data Wrangling

```{r tidy_data}
# Use this R-Chunk to clean & wrangle your data!

```

## Data Visualization

```{r plot_data}
# Use this R-Chunk to plot & visualize your data!

```

## Conclusions
