---
title: "CASE STUDY TITLE"
author: "YOUR NAME"
date: "`r format(Sys.time(), '%B %d, %Y')`"
output:
  html_document:  
    keep_md: true
    toc: true
    toc_float: true
    code_folding: hide
    fig_height: 6
    fig_width: 12
    fig_align: 'center'
---

```{r, echo=FALSE}
knitr::opts_chunk$set(echo = TRUE, message = FALSE, warning = FALSE)
```

```{r load_libraries, include=FALSE}
# Use this R-Chunk to load all your libraries!
#install.packages("tidyverse") # run this line once in console to get package
library(tidyverse)

```

```{r load_data}
# Use this R-Chunk to import all your datasets!
library(USAboundaries)
library(sf)
library(tidyverse)

```

## Background

_Place Task Background Here_

## Data Wrangling

```{r tidy_data}
# Use this R-Chunk to clean & wrangle your data!
devtools::install_github("ropensci/USAboundaries")
devtools::install_github("ropensci/USAboundariesData")


View(idaho)

plot(idaho$geometry)

ggplot()+geom_sf(data=idaho)+geom_sf(data=Idahoco)+geom_sf(data=Idahoci)

Idahoci<-us_cities(state="Idaho")
idaho <- us_states(states = "Idaho")
Idahoco<-us_counties(state="Idaho")


```

## Data Visualization

```{r plot_data}
# Use this R-Chunk to plot & visualize your data!

```

## Conclusions
